spring:
  application:
    name: shortURL
  datasource:
    url: jdbc:postgresql://localhost:5437/shorturl
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

app:
  url:
    base: http://localhost:8080/

